[build]
  command = "echo 'Skipping build since dist is provided'"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "https://webshield-security-platform.vercel.app/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
